// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgN0RvGOhHDQV5Wc7-4MDIry7ZiluFOJQ',
    appId: '1:893487649041:web:09808ecc8b2b38dac1bcb0',
    messagingSenderId: '893487649041',
    projectId: 'duofy-mobile',
    authDomain: 'duofy-mobile.firebaseapp.com',
    storageBucket: 'duofy-mobile.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC60Cuy9ppgsEar_SiQZXZlnT8WwsWEL1k',
    appId: '1:893487649041:android:bc141c5e7a34db44c1bcb0',
    messagingSenderId: '893487649041',
    projectId: 'duofy-mobile',
    storageBucket: 'duofy-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCzekcgP7issZ9ozkvkBocm94IOLUmPs8',
    appId: '1:893487649041:ios:d7017f4e1f10bac2c1bcb0',
    messagingSenderId: '893487649041',
    projectId: 'duofy-mobile',
    storageBucket: 'duofy-mobile.firebasestorage.app',
    iosBundleId: 'com.example.duofy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCzekcgP7issZ9ozkvkBocm94IOLUmPs8',
    appId: '1:893487649041:ios:d7017f4e1f10bac2c1bcb0',
    messagingSenderId: '893487649041',
    projectId: 'duofy-mobile',
    storageBucket: 'duofy-mobile.firebasestorage.app',
    iosBundleId: 'com.example.duofy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgN0RvGOhHDQV5Wc7-4MDIry7ZiluFOJQ',
    appId: '1:893487649041:web:257a39e69050c3f0c1bcb0',
    messagingSenderId: '893487649041',
    projectId: 'duofy-mobile',
    authDomain: 'duofy-mobile.firebaseapp.com',
    storageBucket: 'duofy-mobile.firebasestorage.app',
  );
}
