// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        // Native firebase_core does not support Linux, so this getter is
        // never called there — FbCore initializes firedart directly using
        // [linuxApiKey] and [linuxProjectId] below. Returning the web options
        // keeps the type signature non-nullable in case a caller bypasses the
        // platform check.
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Linux desktop uses firedart instead of the native Firebase SDK. firedart
  /// only needs the project's web API key (used against Identity Toolkit) and
  /// the project id (used as the Firestore database parent).
  static const String linuxApiKey = 'AIzaSyC6BuQvYUAb5kFd5W2tazuD0kAtTSuYMfs';
  static const String linuxProjectId = 'duofy-database';

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6BuQvYUAb5kFd5W2tazuD0kAtTSuYMfs',
    appId: '1:627087433319:web:692ecabeaf47717f79fec2',
    messagingSenderId: '627087433319',
    projectId: 'duofy-database',
    authDomain: 'duofy-database.firebaseapp.com',
    storageBucket: 'duofy-database.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsQEnlNNjins5B16wGYuAiWTNA1I6OPWQ',
    appId: '1:627087433319:android:eabb5c3edb1dddb079fec2',
    messagingSenderId: '627087433319',
    projectId: 'duofy-database',
    storageBucket: 'duofy-database.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIrk933a1Znimvs9Ge7YwgdxmTOE0tjtc',
    appId: '1:627087433319:ios:7621750a6702416379fec2',
    messagingSenderId: '627087433319',
    projectId: 'duofy-database',
    storageBucket: 'duofy-database.firebasestorage.app',
    iosBundleId: 'com.example.duofy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIrk933a1Znimvs9Ge7YwgdxmTOE0tjtc',
    appId: '1:627087433319:ios:7621750a6702416379fec2',
    messagingSenderId: '627087433319',
    projectId: 'duofy-database',
    storageBucket: 'duofy-database.firebasestorage.app',
    iosBundleId: 'com.example.duofy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6BuQvYUAb5kFd5W2tazuD0kAtTSuYMfs',
    appId: '1:627087433319:web:9054103b7c754b1079fec2',
    messagingSenderId: '627087433319',
    projectId: 'duofy-database',
    authDomain: 'duofy-database.firebaseapp.com',
    storageBucket: 'duofy-database.firebasestorage.app',
  );

}